In [1]:
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import mnist

In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
X_train.shape, y_train.shape

((60000, 28, 28), (60000,))

In [4]:
X_test.shape, y_test.shape

((10000, 28, 28), (10000,))

In [5]:
X_train = X_train.reshape(X_train.shape[0], 28,28,1)
X_train.shape

(60000, 28, 28, 1)

In [6]:
X_test = X_test.reshape(X_test.shape[0], 28,28,1)
X_test.shape

(10000, 28, 28, 1)

In [7]:
print(y_train.shape)
print(y_train[:10])

(60000,)
[5 0 4 1 9 2 1 3 1 4]


In [8]:
from tensorflow.keras.utils import to_categorical

In [9]:
Y_train = to_categorical(y_train)
Y_test = to_categorical(y_test)

In [10]:
print(Y_train.shape)
print(Y_train[:3])

(60000, 10)
[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [11]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten

In [12]:
model = Sequential()

model.add(Conv2D(filters=8, kernel_size=(3, 3), activation="sigmoid", padding="same", input_shape=(28,28,1)))

model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))

model.add(Conv2D(filters=8, kernel_size=(3, 3), activation="sigmoid", padding="same"))

model.add(MaxPooling2D(pool_size=(2,2), strides=(2,2)))

model.add(Flatten())

model.add(Dense(units=128, activation="sigmoid"))

model.add(Dense(units=10, activation="softmax"))

model.compile(loss="cateforical_crossentropy", optimizer="adam", metrics=["accuracy"])