In [1]:
import numpy as np 
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
#데이터 생성
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([0,1,1,0])

In [3]:
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [4]:
y

array([0, 1, 1, 0])

In [5]:
model = Sequential()

model.add(Dense(units=32,
                input_dim=2,
                activation="sigmoid"))

model.add(Dense(units=1,
                activation="sigmoid"))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                96        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 129
Trainable params: 129
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.compile(loss="binary_crossentropy",
              optimizer="adam",
              metrics=["accuracy"])

In [8]:
model.fit(X,
          y,
          epochs=1000,
          verbose=0)

In [9]:
evalu = model.evaluate(X, y, verbose=0)
print("loss :",evalu[0])
print("accuracy :",evalu[1])

loss : 0.11377810686826706
accuracy : 1.0


In [20]:
model.predict(X)

array([[0.20988378],
       [0.73770076],
       [0.73675615],
       [0.29836544]], dtype=float32)

In [10]:
model.get_weights()

[array([[-1.5941303 , -1.7721188 , -1.0900099 ,  1.6480597 ,  1.7505685 ,
         -1.486473  ,  1.5770949 ,  1.8043411 ,  1.4267787 , -1.8001679 ,
         -1.6378994 ,  1.5681337 ,  1.6335386 ,  0.35535464, -1.0172529 ,
         -1.7147435 , -1.5178962 ,  1.7110975 , -1.1028291 , -1.8772471 ,
          1.2261933 , -0.9709985 , -1.4018985 , -1.8309996 , -1.8141352 ,
          0.75560796, -1.0022492 , -1.5630118 , -1.0636876 , -1.0950493 ,
         -1.0281371 ,  1.890774  ],
        [-1.827214  ,  1.6173401 , -0.86650956, -1.6544961 , -1.7228527 ,
         -1.7745731 ,  1.6473494 , -1.7219896 ,  1.8056806 ,  1.7912518 ,
         -1.734187  , -1.59177   , -1.6326028 ,  0.43426105, -0.7640549 ,
          1.7819109 , -1.7338791 , -1.6905324 , -0.8623642 ,  1.6880143 ,
          0.9923883 , -0.73746085,  1.8607494 ,  1.8164237 ,  1.7650933 ,
          0.49102896, -0.757287  ,  1.7351056 , -0.8183942 , -0.8737381 ,
         -0.7645202 , -1.6891757 ]], dtype=float32),
 array([ 0.1609963 , -1

## 다중분류

In [38]:
X = np.array([[0,0],[0,1],[1,0],[1,1]])
y = np.array([[1,0],[0,1],[0,1],[1,0]])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [39]:
y

array([[1, 0],
       [0, 1],
       [0, 1],
       [1, 0]])

In [45]:
model = Sequential()
model.add(Dense(units=32, input_dim = 2, activation="sigmoid"))

model.add(Dense(units=2,
                activation="softmax"))

In [46]:
model.compile(loss="categorical_crossentropy",
             optimizer="RMSprop",
             metrics=["accuracy"])

In [47]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_8 (Dense)              (None, 32)                96        
_________________________________________________________________
dense_9 (Dense)              (None, 2)                 66        
Total params: 162
Trainable params: 162
Non-trainable params: 0
_________________________________________________________________


In [48]:
model.fit(X, y, epochs=2000)

Train on 4 samples
Epoch 1/2000
4/4 [==============================] - 0s 108ms/sample - loss: 0.6980 - accuracy: 0.2500
Epoch 2/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6956 - accuracy: 0.5000
Epoch 3/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6955 - accuracy: 0.5000
Epoch 4/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.6954 - accuracy: 0.5000
Epoch 5/2000
4/4 [==============================] - 0s 998us/sample - loss: 0.6953 - accuracy: 0.5000
Epoch 6/2000
4/4 [==============================] - 0s 749us/sample - loss: 0.6952 - accuracy: 0.5000
Epoch 7/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.6951 - accuracy: 0.5000
Epoch 8/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6950 - accuracy: 0.5000
Epoch 9/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.6950 - accuracy: 0.5000
Epoch 10/2000
4/4 [==============================] - 0s 1ms/sample - l

Epoch 82/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6922 - accuracy: 0.5000
Epoch 83/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.6922 - accuracy: 0.5000
Epoch 84/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6922 - accuracy: 0.5000
Epoch 85/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6921 - accuracy: 0.5000
Epoch 86/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.6921 - accuracy: 0.5000
Epoch 87/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6921 - accuracy: 0.5000
Epoch 88/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6921 - accuracy: 0.5000
Epoch 89/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.6920 - accuracy: 0.5000
Epoch 90/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.6920 - accuracy: 0.5000
Epoch 91/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.692

Epoch 162/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6903 - accuracy: 0.7500
Epoch 163/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.6902 - accuracy: 0.5000
Epoch 164/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6902 - accuracy: 0.7500
Epoch 165/2000
4/4 [==============================] - 0s 749us/sample - loss: 0.6902 - accuracy: 0.5000
Epoch 166/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.6901 - accuracy: 0.7500
Epoch 167/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.6901 - accuracy: 0.5000
Epoch 168/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6901 - accuracy: 0.7500
Epoch 169/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6900 - accuracy: 0.5000
Epoch 170/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6900 - accuracy: 0.7500
Epoch 171/2000
4/4 [==============================] - 0s 749us/sample - 

Epoch 242/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.6868 - accuracy: 0.7500
Epoch 243/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6867 - accuracy: 0.2500
Epoch 244/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6866 - accuracy: 0.7500
Epoch 245/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.6866 - accuracy: 0.2500
Epoch 246/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6865 - accuracy: 0.7500
Epoch 247/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6864 - accuracy: 0.2500
Epoch 248/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6864 - accuracy: 0.7500
Epoch 249/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6863 - accuracy: 0.2500
Epoch 250/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.6863 - accuracy: 0.7500
Epoch 251/2000
4/4 [==============================] - 0s 1ms/sample - los

Epoch 322/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6802 - accuracy: 0.7500
Epoch 323/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.6801 - accuracy: 0.7500
Epoch 324/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6800 - accuracy: 0.7500
Epoch 325/2000
4/4 [==============================] - 0s 500us/sample - loss: 0.6799 - accuracy: 0.7500
Epoch 326/2000
4/4 [==============================] - 0s 500us/sample - loss: 0.6798 - accuracy: 0.7500
Epoch 327/2000
4/4 [==============================] - 0s 500us/sample - loss: 0.6796 - accuracy: 0.7500
Epoch 328/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6795 - accuracy: 0.7500
Epoch 329/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6794 - accuracy: 0.7500
Epoch 330/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6793 - accuracy: 0.7500
Epoch 331/2000
4/4 [==============================] - 0s 1ms/sampl

Epoch 402/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6689 - accuracy: 0.7500
Epoch 403/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6688 - accuracy: 1.0000
Epoch 404/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6686 - accuracy: 0.7500
Epoch 405/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6684 - accuracy: 1.0000
Epoch 406/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.6682 - accuracy: 0.7500
Epoch 407/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6681 - accuracy: 1.0000
Epoch 408/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6679 - accuracy: 0.7500
Epoch 409/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6677 - accuracy: 1.0000
Epoch 410/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6675 - accuracy: 0.7500
Epoch 411/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.

Epoch 482/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6514 - accuracy: 1.0000
Epoch 483/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6511 - accuracy: 1.0000
Epoch 484/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6508 - accuracy: 1.0000
Epoch 485/2000
4/4 [==============================] - 0s 999us/sample - loss: 0.6506 - accuracy: 1.0000
Epoch 486/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6503 - accuracy: 1.0000
Epoch 487/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6500 - accuracy: 1.0000
Epoch 488/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6497 - accuracy: 1.0000
Epoch 489/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6495 - accuracy: 1.0000
Epoch 490/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6492 - accuracy: 1.0000
Epoch 491/2000
4/4 [==============================] - 0s 1ms/sample - loss

Epoch 562/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6262 - accuracy: 1.0000
Epoch 563/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6259 - accuracy: 1.0000
Epoch 564/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6255 - accuracy: 1.0000
Epoch 565/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.6251 - accuracy: 1.0000
Epoch 566/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6248 - accuracy: 1.0000
Epoch 567/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6244 - accuracy: 1.0000
Epoch 568/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.6240 - accuracy: 1.0000
Epoch 569/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6236 - accuracy: 1.0000
Epoch 570/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.6233 - accuracy: 1.0000
Epoch 571/2000
4/4 [==============================] - 0s 997us/sam

Epoch 642/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5931 - accuracy: 1.0000
Epoch 643/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.5926 - accuracy: 1.0000
Epoch 644/2000
4/4 [==============================] - 0s 748us/sample - loss: 0.5922 - accuracy: 1.0000
Epoch 645/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5917 - accuracy: 1.0000
Epoch 646/2000
4/4 [==============================] - 0s 749us/sample - loss: 0.5912 - accuracy: 1.0000
Epoch 647/2000
4/4 [==============================] - 0s 500us/sample - loss: 0.5908 - accuracy: 1.0000
Epoch 648/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5903 - accuracy: 1.0000
Epoch 649/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5898 - accuracy: 1.0000
Epoch 650/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.5893 - accuracy: 1.0000
Epoch 651/2000
4/4 [==============================] - 0s 750us/sample -

Epoch 722/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5518 - accuracy: 1.0000
Epoch 723/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.5513 - accuracy: 1.0000
Epoch 724/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5507 - accuracy: 1.0000
Epoch 725/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5501 - accuracy: 1.0000
Epoch 726/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5496 - accuracy: 1.0000
Epoch 727/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5490 - accuracy: 1.0000
Epoch 728/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5484 - accuracy: 1.0000
Epoch 729/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5478 - accuracy: 1.0000
Epoch 730/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.5473 - accuracy: 1.0000
Epoch 731/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.5

Epoch 802/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.5026 - accuracy: 1.0000
Epoch 803/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5019 - accuracy: 1.0000
Epoch 804/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5013 - accuracy: 1.0000
Epoch 805/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.5006 - accuracy: 1.0000
Epoch 806/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.5000 - accuracy: 1.0000
Epoch 807/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.4993 - accuracy: 1.0000
Epoch 808/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.4986 - accuracy: 1.0000
Epoch 809/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.4979 - accuracy: 1.0000
Epoch 810/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.4973 - accuracy: 1.0000
Epoch 811/2000
4/4 [==============================] - 0s 750us/sample - loss

Epoch 882/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.4465 - accuracy: 1.0000
Epoch 883/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.4457 - accuracy: 1.0000
Epoch 884/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.4450 - accuracy: 1.0000
Epoch 885/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.4443 - accuracy: 1.0000
Epoch 886/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.4435 - accuracy: 1.0000
Epoch 887/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.4428 - accuracy: 1.0000
Epoch 888/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.4420 - accuracy: 1.0000
Epoch 889/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.4413 - accuracy: 1.0000
Epoch 890/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.4406 - accuracy: 1.0000
Epoch 891/2000
4/4 [==============================] - 0s 1ms/sample - loss

Epoch 962/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.3856 - accuracy: 1.0000
Epoch 963/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.3848 - accuracy: 1.0000
Epoch 964/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.3840 - accuracy: 1.0000
Epoch 965/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.3832 - accuracy: 1.0000
Epoch 966/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.3824 - accuracy: 1.0000
Epoch 967/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.3816 - accuracy: 1.0000
Epoch 968/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.3809 - accuracy: 1.0000
Epoch 969/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.3801 - accuracy: 1.0000
Epoch 970/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.3793 - accuracy: 1.0000
Epoch 971/2000
4/4 [==============================] - 0s 1ms/sample - 

Epoch 1041/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.3235 - accuracy: 1.0000
Epoch 1042/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.3227 - accuracy: 1.0000
Epoch 1043/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.3219 - accuracy: 1.0000
Epoch 1044/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.3212 - accuracy: 1.0000
Epoch 1045/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.3204 - accuracy: 1.0000
Epoch 1046/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.3196 - accuracy: 1.0000
Epoch 1047/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.3188 - accuracy: 1.0000
Epoch 1048/2000
4/4 [==============================] - 0s 500us/sample - loss: 0.3180 - accuracy: 1.0000
Epoch 1049/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.3172 - accuracy: 1.0000
Epoch 1050/2000
4/4 [==============================] - 0s 1ms/s

Epoch 1120/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2628 - accuracy: 1.0000
Epoch 1121/2000
4/4 [==============================] - 0s 999us/sample - loss: 0.2620 - accuracy: 1.0000
Epoch 1122/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.2613 - accuracy: 1.0000
Epoch 1123/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2605 - accuracy: 1.0000
Epoch 1124/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.2598 - accuracy: 1.0000
Epoch 1125/2000
4/4 [==============================] - 0s 500us/sample - loss: 0.2590 - accuracy: 1.0000
Epoch 1126/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2583 - accuracy: 1.0000
Epoch 1127/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.2575 - accuracy: 1.0000
Epoch 1128/2000
4/4 [==============================] - 0s 999us/sample - loss: 0.2568 - accuracy: 1.0000
Epoch 1129/2000
4/4 [==============================] - 0s 1m

Epoch 1199/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.2062 - accuracy: 1.0000
Epoch 1200/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.2056 - accuracy: 1.0000
Epoch 1201/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.2049 - accuracy: 1.0000
Epoch 1202/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.2042 - accuracy: 1.0000
Epoch 1203/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2035 - accuracy: 1.0000
Epoch 1204/2000
4/4 [==============================] - 0s 500us/sample - loss: 0.2029 - accuracy: 1.0000
Epoch 1205/2000
4/4 [==============================] - 0s 502us/sample - loss: 0.2022 - accuracy: 1.0000
Epoch 1206/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.2015 - accuracy: 1.0000
Epoch 1207/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.2008 - accuracy: 1.0000
Epoch 1208/2000
4/4 [==============================] - 0s 1

Epoch 1278/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.1563 - accuracy: 1.0000
Epoch 1279/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1557 - accuracy: 1.0000
Epoch 1280/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.1551 - accuracy: 1.0000
Epoch 1281/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.1546 - accuracy: 1.0000
Epoch 1282/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1540 - accuracy: 1.0000
Epoch 1283/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.1534 - accuracy: 1.0000
Epoch 1284/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.1528 - accuracy: 1.0000
Epoch 1285/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.1522 - accuracy: 1.0000
Epoch 1286/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.1517 - accuracy: 1.0000
Epoch 1287/2000
4/4 [==============================] - 0s 1

Epoch 1357/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1144 - accuracy: 1.0000
Epoch 1358/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1139 - accuracy: 1.0000
Epoch 1359/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1134 - accuracy: 1.0000
Epoch 1360/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1129 - accuracy: 1.0000
Epoch 1361/2000
4/4 [==============================] - 0s 748us/sample - loss: 0.1125 - accuracy: 1.0000
Epoch 1362/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.1120 - accuracy: 1.0000
Epoch 1363/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1115 - accuracy: 1.0000
Epoch 1364/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.1110 - accuracy: 1.0000
Epoch 1365/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.1106 - accuracy: 1.0000
Epoch 1366/2000
4/4 [==============================] - 0s 1ms/sa

Epoch 1436/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0808 - accuracy: 1.0000
Epoch 1437/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0804 - accuracy: 1.0000
Epoch 1438/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0800 - accuracy: 1.0000
Epoch 1439/2000
4/4 [==============================] - 0s 749us/sample - loss: 0.0797 - accuracy: 1.0000
Epoch 1440/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0793 - accuracy: 1.0000
Epoch 1441/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0789 - accuracy: 1.0000
Epoch 1442/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0786 - accuracy: 1.0000
Epoch 1443/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0782 - accuracy: 1.0000
Epoch 1444/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0778 - accuracy: 1.0000
Epoch 1445/2000
4/4 [==============================] - 0s 1ms/sampl

Epoch 1515/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0551 - accuracy: 1.0000
Epoch 1516/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0548 - accuracy: 1.0000
Epoch 1517/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0545 - accuracy: 1.0000
Epoch 1518/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0542 - accuracy: 1.0000
Epoch 1519/2000
4/4 [==============================] - 0s 999us/sample - loss: 0.0540 - accuracy: 1.0000
Epoch 1520/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0537 - accuracy: 1.0000
Epoch 1521/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0534 - accuracy: 1.0000
Epoch 1522/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0532 - accuracy: 1.0000
Epoch 1523/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0529 - accuracy: 1.0000
Epoch 1524/2000
4/4 [==============================] - 0s 1ms/sampl

Epoch 1594/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0362 - accuracy: 1.0000
Epoch 1595/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.0360 - accuracy: 1.0000
Epoch 1596/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0358 - accuracy: 1.0000
Epoch 1597/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0356 - accuracy: 1.0000
Epoch 1598/2000
4/4 [==============================] - 0s 500us/sample - loss: 0.0354 - accuracy: 1.0000
Epoch 1599/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0353 - accuracy: 1.0000
Epoch 1600/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0351 - accuracy: 1.0000
Epoch 1601/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.0349 - accuracy: 1.0000
Epoch 1602/2000
4/4 [==============================] - 0s 999us/sample - loss: 0.0347 - accuracy: 1.0000
Epoch 1603/2000
4/4 [==============================] - 0s 

Epoch 1673/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.0230 - accuracy: 1.0000
Epoch 1674/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0229 - accuracy: 1.0000
Epoch 1675/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0227 - accuracy: 1.0000
Epoch 1676/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0226 - accuracy: 1.0000
Epoch 1677/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0225 - accuracy: 1.0000
Epoch 1678/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0223 - accuracy: 1.0000
Epoch 1679/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0222 - accuracy: 1.0000
Epoch 1680/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0221 - accuracy: 1.0000
Epoch 1681/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.0219 - accuracy: 1.0000
Epoch 1682/2000
4/4 [==============================] - 0s 750us/sam

Epoch 1752/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.0141 - accuracy: 1.0000
Epoch 1753/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0140 - accuracy: 1.0000
Epoch 1754/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0140 - accuracy: 1.0000
Epoch 1755/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0139 - accuracy: 1.0000
Epoch 1756/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0138 - accuracy: 1.0000
Epoch 1757/2000
4/4 [==============================] - 0s 2ms/sample - loss: 0.0137 - accuracy: 1.0000
Epoch 1758/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0136 - accuracy: 1.0000
Epoch 1759/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0135 - accuracy: 1.0000
Epoch 1760/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0134 - accuracy: 1.0000
Epoch 1761/2000
4/4 [==============================] - 0s 750us/sam

Epoch 1831/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0084 - accuracy: 1.0000
Epoch 1832/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0083 - accuracy: 1.0000
Epoch 1833/2000
4/4 [==============================] - 0s 749us/sample - loss: 0.0083 - accuracy: 1.0000
Epoch 1834/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0082 - accuracy: 1.0000
Epoch 1835/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.0082 - accuracy: 1.0000
Epoch 1836/2000
4/4 [==============================] - 0s 749us/sample - loss: 0.0081 - accuracy: 1.0000
Epoch 1837/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0081 - accuracy: 1.0000
Epoch 1838/2000
4/4 [==============================] - 0s 749us/sample - loss: 0.0080 - accuracy: 1.0000
Epoch 1839/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.0079 - accuracy: 1.0000
Epoch 1840/2000
4/4 [==============================] - 0s 

Epoch 1910/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.0048 - accuracy: 1.0000
Epoch 1911/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0048 - accuracy: 1.0000
Epoch 1912/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0048 - accuracy: 1.0000
Epoch 1913/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0047 - accuracy: 1.0000
Epoch 1914/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0047 - accuracy: 1.0000
Epoch 1915/2000
4/4 [==============================] - 0s 749us/sample - loss: 0.0047 - accuracy: 1.0000
Epoch 1916/2000
4/4 [==============================] - 0s 749us/sample - loss: 0.0046 - accuracy: 1.0000
Epoch 1917/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0046 - accuracy: 1.0000
Epoch 1918/2000
4/4 [==============================] - 0s 501us/sample - loss: 0.0046 - accuracy: 1.0000
Epoch 1919/2000
4/4 [==============================] - 0s

Epoch 1989/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0027 - accuracy: 1.0000
Epoch 1990/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0027 - accuracy: 1.0000
Epoch 1991/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.0027 - accuracy: 1.0000
Epoch 1992/2000
4/4 [==============================] - 0s 750us/sample - loss: 0.0026 - accuracy: 1.0000
Epoch 1993/2000
4/4 [==============================] - 0s 1000us/sample - loss: 0.0026 - accuracy: 1.0000
Epoch 1994/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0026 - accuracy: 1.0000
Epoch 1995/2000
4/4 [==============================] - 0s 999us/sample - loss: 0.0026 - accuracy: 1.0000
Epoch 1996/2000
4/4 [==============================] - 0s 1ms/sample - loss: 0.0026 - accuracy: 1.0000
Epoch 1997/2000
4/4 [==============================] - 0s 751us/sample - loss: 0.0025 - accuracy: 1.0000
Epoch 1998/2000
4/4 [==============================] - 0s 99

In [49]:
model.evaluate(X, y, verbose=0)

[0.0024592061527073383, 1.0]

In [51]:
model.predict(X) 

array([[0.99758947, 0.00241049],
       [0.00239587, 0.9976042 ],
       [0.00264109, 0.99735886],
       [0.9976228 , 0.00237723]], dtype=float32)

In [52]:
model.predict_classes(X)

array([0, 1, 1, 0], dtype=int64)

In [21]:
model.predict_classes(X)

array([[0],
       [1],
       [1],
       [0]])